### PR TITLE
Support for custom options

### PR DESCRIPTION
**Pull request by dinosaurioh**
- Support for custom apps. (Readme said customs applications IDs were supported, but actually they weren't.)
- Tried improving readability and reducing some code.
- Catch error now displays current application instead of just Youtube.
- Error number sometimes is also returned by Discord inside ".code" property, added an extra created_at check just to be sure the code we are getting back is valid and it's not part of an error response. Also, prior condition was checking for ".error" property but seems like Discord returns errors inside ".errors".

### CODE REVIEW

**Comment by Lermatroid** [comment]
Are custom applications supported at the moment (as in are you able to create apps for discord activities)?

**Comment by dinosaurioh** [comment]
No, you can't create new applications by yourself, however you can now pass customs IDs for already existing applications that may not be defined or included in `defaultApplications` object.

**Comment by RemyK888** [comment]
Indeed, it is currently impossible to create your own applications, I hope this function will come soon!
Can i close this pull request ?
RemyK

**Comment by dinosaurioh** [comment]
I'm sorry, I think you missunderstood me.
This pull request isn't for creating custom apps, It's for having the hability of using an ID as a custom option (as readme says).
Also it includes a fix for the currently open issue.

**Comment by RemyK888** [comment]
Okay, thanks a lot, I'll have a look at it, but this option is useless at the moment because as you say, it's impossible to create your own applications.

**Pull request closed without merging**
