### PR TITLE
Added Typescript support with declaration file

### PR DESCRIPTION
**Pull request by 3chospirits**
Made slight adjustments to documentation for accurate typing (client: string) => (client: Discord.Client)

### CODE REVIEW

**Comment by Milo123459** [comment]
+1 @RemyK888

**Comment by Milo123459** [comment]
May I ask why..?

**Comment by RemyK888** [comment]
why what ?

**Comment by RemyK888** [comment]
i have been updated the package

**Comment by Milo123459** [comment]
Why you closed this PR.

**Comment by RemyK888** [comment]
i'll update the repo now

**Comment by Milo123459** [comment]
Oh so you don't give people credits for their contributions. I see.

**Comment by RemyK888** [comment]
no i credited in readme

**Comment by Milo123459** [comment]
Where in the README.

**Comment by RemyK888** [comment]
i haven't update btw i'm reponsding to you

**Comment by Milo123459** [comment]
But there have been other contributions, and there are still no credits in the README.

**Comment by RemyK888** [comment]
no it's the first contribution
i closed pr which were not useful

**Comment by Milo123459** [comment]
There is a thing called merging.

**Comment by RemyK888** [comment]
i know lol

**Comment by Milo123459** [comment]
But you choose to not use it? Why?

**Comment by Milo123459** [comment]
I believe this was merged: https://github.com/RemyK888/discord-together/pull/4

**Comment by RemyK888** [comment]
because the ideas were not interesting (from my point of view)

**Comment by Milo123459** [comment]
But you still merged a PR and you are still not giving any credits. Also, merging makes more sense.

**Comment by RemyK888** [comment]
this pr was before the update in collaboration wih @bela333

**Comment by Milo123459** [comment]
And bela gets credit where?

**Comment by RemyK888** [comment]
image

**Comment by Milo123459** [comment]
Okay.

**Comment by RemyK888** [comment]
if you have other questions, I invite you to join the Discord server, to talk more comfortably (also for the info Bela did not want to be a collaborator of the repo)

**Pull request closed without merging**
